from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Float, Text
from sqlalchemy.orm import relationship
from datetime import datetime
from app.db.database import Base

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    
    # there can be multiple profiles (birth charts) for one user
    profiles = relationship("Profile", back_populates="owner")

class Profile(Base):
    __tablename__ = "profiles"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    name = Column(String, nullable=False) # mother's name, baby's name, or any identifier for the profile
    city = Column(String, nullable=True)
    # Birth Datas
    birth_date = Column(DateTime, nullable=False)
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)

    owner = relationship("User", back_populates="profiles")
    # each profile can have multiple analyses (reports generated by Gemini)
    analyses = relationship("Analysis", back_populates="profile")

class Analysis(Base):
    __tablename__ = "analyses"

    id = Column(Integer, primary_key=True, index=True)
    profile_id = Column(Integer, ForeignKey("profiles.id"))
    
    report_content = Column(Text, nullable=False) # text content generated by Gemini
    created_at = Column(DateTime, default=datetime.utcnow)

    profile = relationship("Profile", back_populates="analyses")